import Head from 'next/head';
import Link from 'next/link';
import Navbar from './Navbar';
import Footer from './Footer';
import FAQ from './FAQ';
import { ArrowLeft, BadgeCheck, Bot, BriefcaseBusiness, Building2, CheckCircle2, Cloud, FileCheck2, FileText, Globe2, LayoutDashboard, MapPinned, Monitor, PackageCheck, ShieldCheck, Smartphone, Store, Truck, Undo2, WalletCards, Wrench } from 'lucide-react';

const Shell = ({children}) => <div dir="rtl" className="min-h-screen bg-[#FDFBF7] text-gray-900"><Navbar/><main>{children}</main><Footer/></div>;
const CTA = ({href,children,className=''}) => <Link href={href} className={`inline-flex items-center justify-center gap-2 rounded-2xl px-7 py-4 font-black ${className}`}>{children}<ArrowLeft className="h-5 w-5"/></Link>;

function PlatformForBusiness(){
 const faqs=[['ما هي منصة بيت الريف للأعمال؟','هي مسار أعمال للشركات ومزودي الخدمات لتنظيم هوية النشاط والتخصصات ومناطق الخدمة وإدارة المتجر والعناصر والأدوات بحسب حالة الحساب والخطة.'],['هل التسجيل يعني النشر مباشرة؟','لا. النشر العام يرتبط باكتمال البيانات والتحقق وحالة الحساب والخطة والصلاحيات المفعلة.'],['هل تعمل المنصة على الكمبيوتر والهاتف؟','نعم، يمكن استخدام بيت الريف من متصفح الكمبيوتر، كما يتوفر تطبيق بيت الريف على Android.'],['ما دور وياك؟','وياك مساعد أعمال داخل منظومة بيت الريف يعمل مع سياق الحساب ويساعد في تنظيم المعلومات والمحتوى والعناصر والمستندات ضمن الصلاحيات المتاحة.']];
 return <Shell><Head><title>كيف تعمل منصة بيت الريف للأعمال | بيت الريف</title><meta name="description" content="اكتشف رحلة الشركة داخل بيت الريف من إنشاء الحساب والتحقق إلى المتجر والعناصر ووياك وإدارة الأعمال من الكمبيوتر وAndroid."/><link rel="canonical" href="https://bietalreef.ae/platform-for-business"/></Head>
 <section className="relative overflow-hidden bg-[#0F3F1A] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(212,175,55,.3),transparent_32%)]"/><div className="relative mx-auto max-w-7xl px-4 py-20 md:py-28"><span className="rounded-full border border-[#D4AF37]/50 bg-[#D4AF37]/15 px-4 py-2 text-sm font-black text-[#F3D46B]">منصة بيت الريف للأعمال</span><h1 className="mt-7 max-w-5xl text-4xl font-black leading-tight md:text-6xl">من حساب شركتك إلى منظومة أعمال رقمية متكاملة</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-white/85">أنشئ حساب نشاطك، استكمل التحقق، فعّل الخطة المناسبة، ثم أدر ملف الشركة والمتجر والمنتجات والخدمات والعروض والمستندات ووياك من منظومة واحدة.</p><div className="mt-9"><CTA href="/join-biet-alreef" className="bg-[#D4AF37] text-[#0F3F1A]">ضم شركتك إلى بيت الريف</CTA></div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-black">رحلة الشركة في أربع مراحل</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[['01','إنشاء الحساب','تسجيل النشاط وبياناته الأساسية.'],['02','التحقق','استكمال الهوية والتخصصات ومناطق الخدمة.'],['03','الخطة والصلاحيات','تفعيل الأدوات والحصص المناسبة.'],['04','إدارة الأعمال','إدارة الملف والمتجر والعناصر ووياك.']].map(([n,t,d])=><article key={n} className="rounded-[2rem] border border-[#E6DCC8] bg-white p-7 shadow-sm"><span className="text-4xl font-black text-[#D4AF37]">{n}</span><h3 className="mt-5 text-xl font-black">{t}</h3><p className="mt-3 leading-7 text-gray-600">{d}</p></article>)}</div></section>
 <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-6 px-4 lg:grid-cols-2"><article className="rounded-[2rem] bg-[#FFF8E5] p-9"><Building2 className="h-10 w-10 text-[#0F3F1A]"/><h2 className="mt-5 text-3xl font-black">ملف أعمال وليس مجرد حساب</h2><p className="mt-5 leading-9 text-gray-700">هوية النشاط والتخصصات والخدمات ومناطق العمل تصبح أساسًا للمتجر والعناصر والنشر والأدوات.</p></article><article className="rounded-[2rem] bg-[#0F3F1A] p-9 text-white"><LayoutDashboard className="h-10 w-10 text-[#F3D46B]"/><h2 className="mt-5 text-3xl font-black">أدوات نشاطك في مكان واحد</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{[['المتجر',Store],['وياك',Bot],['الملف',BadgeCheck],['الإدارة',LayoutDashboard]].map(([t,I])=><div key={t} className="rounded-2xl bg-white/10 p-4"><I className="h-6 w-6 text-[#F3D46B]"/><b className="mt-3 block">{t}</b></div>)}</div></article></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16"><div className="rounded-[2rem] border border-[#E6DCC8] bg-white p-9"><h2 className="text-3xl font-black">بيت الريف معك في المكتب، في الموقع، وفي كل مكان</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-[#F7F4EC] p-6"><Monitor className="h-8 w-8"/><h3 className="mt-4 text-xl font-black">من الكمبيوتر</h3><p className="mt-2 text-gray-600">إدارة الملف والعناصر والمستندات من المتصفح.</p></div><div className="rounded-3xl bg-[#F7F4EC] p-6"><Smartphone className="h-8 w-8"/><h3 className="mt-4 text-xl font-black">من Android</h3><p className="mt-2 text-gray-600">استمر في العمل أثناء التنقل والموقع.</p></div></div></div></section><FAQ items={faqs} title="أسئلة شائعة حول منصة بيت الريف للأعمال"/><section className="bg-[#0F3F1A] py-16 text-center text-white"><h2 className="text-3xl font-black">ابدأ ببناء حضور شركتك</h2><div className="mt-7"><CTA href="/join-biet-alreef" className="bg-[#D4AF37] text-[#0F3F1A]">ضم شركتك الآن</CTA></div></section></Shell>;
}

function JoinProvider(){
 const faqs=[['هل التسجيل يعني النشر مباشرة؟','لا. النشر العام يرتبط باكتمال بيانات النشاط والتحقق وحالة الحساب والخطة والصلاحيات.'],['من يمكنه الانضمام؟','الشركات ومزودو الخدمات والموردون والمصانع والورش والمهنيون وفق نوع النشاط ومتطلبات التحقق.'],['هل يمكن إضافة خدمات ومنتجات وعروض؟','نعم عندما تسمح الخطة والصلاحيات بذلك وبحسب الحصة المفعلة.'],['هل تضمن بيت الريف عددًا محددًا من العملاء؟','لا. المنصة توفر الحضور الرقمي والاكتشاف وأدوات الأعمال دون ضمان نتائج تجارية أو عدد عملاء محدد.']];
 return <Shell><Head><title>انضم كمزود خدمة إلى بيت الريف | بيت الريف</title><meta name="description" content="سجّل نشاطك كمزود خدمة في بيت الريف واستكمل التخصصات ومناطق العمل والتحقق ثم فعّل الأدوات والنشر وفق خطتك."/><link rel="canonical" href="https://bietalreef.ae/join-provider"/></Head>
 <section className="bg-gradient-to-b from-emerald-50 to-white py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-2 lg:items-center"><div><span className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-black text-emerald-800">فرصة نمو لأعمالك</span><h1 className="mt-6 text-4xl font-black leading-tight text-[#0F3F1A] md:text-6xl">انضم كمزود خدمة إلى بيت الريف</h1><p className="mt-6 text-lg leading-9 text-gray-600">حوّل نشاطك إلى حضور مهني منظم مع ملف أعمال وتخصصات ومناطق خدمة ومتجر وأدوات تشغيل بحسب حالة الحساب والخطة.</p><div className="mt-8"><CTA href="/providers/register" className="bg-[#0F3F1A] text-white">ابدأ تسجيل شركتك</CTA></div></div><div className="rounded-[2rem] bg-[#0F3F1A] p-8 text-white"><Building2 className="h-12 w-12 text-[#F3D46B]"/><h2 className="mt-5 text-3xl font-black">حضور مهني قابل للتحقق</h2><div className="mt-6 space-y-3">{['هوية نشاط واضحة','تخصصات ومناطق عمل','مراجعة قبل النشر','متجر وعناصر حسب الخطة'].map(x=><div key={x} className="flex gap-3 rounded-2xl bg-white/10 p-4"><CheckCircle2 className="h-5 w-5 text-[#F3D46B]"/><b>{x}</b></div>)}</div></div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-black">مزايا الانضمام</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[[BadgeCheck,'ملف مهني موثق','قدّم نشاطك بصورة واضحة بعد اكتمال البيانات والتحقق.'],[MapPinned,'مناطق خدمة','اربط النشاط بالمناطق التي تعمل بها.'],[Store,'متجر وعناصر','أدر العناصر المسموحة حسب الخطة.'],[FileCheck2,'مراجعة قبل النشر','تحقق من البيانات قبل الظهور العام.'],[Wrench,'أدوات تشغيل','استخدم الأدوات حسب الصلاحيات.'],[Building2,'هوية أعمال موحدة','اجمع معلومات الشركة في حساب واحد.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-[#E6DCC8] bg-white p-7"><I className="h-8 w-8 text-[#0F3F1A]"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
 <section className="bg-[#F4F8F4] py-16"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">خطوات الانضمام</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','سجّل النشاط'],['02','استكمل الملف'],['03','أرسل للمراجعة'],['04','فعّل أدواتك']].map(([n,t])=><div key={n} className="rounded-3xl bg-white p-6"><span className="text-3xl font-black text-emerald-700">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section><FAQ items={faqs} title="الأسئلة الشائعة حول الانضمام كمزود خدمة"/><section className="bg-[#0F3F1A] py-16 text-center text-white"><h2 className="text-3xl font-black">ابدأ بناء حضور نشاطك</h2><div className="mt-7"><CTA href="/providers/register" className="bg-[#D4AF37] text-[#0F3F1A]">ابدأ التسجيل</CTA></div></section></Shell>;
}

function BusinessSolutions(){
 const faqs=[['ما حلول الأعمال التي تقدمها بيت الريف؟','تشمل الحضور الرقمي والمتجر وأدوات النشر وإدارة النشاط، إضافة إلى Google Cloud وGoogle Workspace ووياك وفق احتياج الشركة.'],['هل يجب الاشتراك في جميع الحلول؟','لا. يتم اختيار الخدمة أو النطاق المناسب بحسب احتياج الشركة والخطة.'],['هل خدمات Google هي نفسها أدوات منصة بيت الريف؟','لا. أدوات المنصة تخص حساب بيت الريف، بينما Google Cloud وGoogle Workspace خدمات رقمية مستقلة في نطاقها.'],['هل تضمن الحلول نتائج مبيعات أو ترتيب بحث؟','لا. تقدم بيت الريف الأدوات والخدمات دون ضمان أرقام مبيعات أو ترتيب بحث محدد.']];
 return <Shell><Head><title>حلول وخدمات بيت الريف للأعمال | بيت الريف</title><meta name="description" content="حلول رقمية للشركات تشمل الحضور المهني والمتجر وGoogle Cloud وGoogle Workspace ووياك وأدوات إدارة النشاط."/><link rel="canonical" href="https://bietalreef.ae/business-solutions"/></Head>
 <section className="bg-gradient-to-l from-[#0E315A] to-[#0F3F1A] py-20 text-white"><div className="mx-auto max-w-7xl px-4 text-center"><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-black">حلول متكاملة للأعمال</span><h1 className="mx-auto mt-6 max-w-5xl text-4xl font-black leading-tight md:text-6xl">حلول رقمية تجمع حضور شركتك وتشغيلها في مسارات واضحة</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-white/80">من ملف الشركة والمتجر إلى Google Cloud وGoogle Workspace ووياك، تختار الشركة ما تحتاجه فعليًا.</p><div className="mt-8"><CTA href="/contact" className="bg-[#D4AF37] text-[#0F3F1A]">تحدث مع فريق بيت الريف</CTA></div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[[Globe2,'الحضور الرقمي','ملف أعمال ومسارات نشر واكتشاف منظمة.'],[Store,'المتجر والعناصر','منتجات وخدمات وعروض وسياسات حسب الخطة.'],[Cloud,'Google Cloud','تطبيقات وبيانات وذكاء اصطناعي وMaps وتكاملات.'],[BriefcaseBusiness,'Google Workspace','بريد الشركة وDrive وMeet وCalendar وإدارة المستخدمين.'],[Bot,'وياك','مساعد أعمال داخل سياق الحساب.'],[LayoutDashboard,'إدارة النشاط','مسارات تشغيل للأدوات والعناصر والمستندات.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-slate-200 bg-white p-7"><I className="h-8 w-8 text-[#0E315A]"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
 <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-6 px-4 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[2rem] bg-[#0E315A] p-9 text-white"><h2 className="text-3xl font-black">كيف نحدد الحل المناسب؟</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{[['01','حدد المشكلة'],['02','راجع الوضع الحالي'],['03','اختر النطاق'],['04','ابدأ التنفيذ']].map(([n,t])=><div key={n} className="rounded-2xl bg-white/10 p-5"><span className="text-[#F3D46B]">{n}</span><b className="mt-3 block">{t}</b></div>)}</div></article><aside className="rounded-[2rem] bg-[#FFF8E5] p-9"><FileText className="h-9 w-9"/><h2 className="mt-5 text-2xl font-black">كل خدمة لها نطاق مستقل</h2><p className="mt-4 leading-8 text-gray-700">حلول منصة بيت الريف ليست Google Cloud وليست Google Workspace. كل خدمة لها هدف ونطاق وشروط مستقلة ويتم ربطها عند الحاجة.</p></aside></div></section><FAQ items={faqs} title="الأسئلة الشائعة حول حلول بيت الريف للأعمال"/><section className="bg-[#0F3F1A] py-16 text-center text-white"><h2 className="text-3xl font-black">ابدأ من احتياج شركتك الحقيقي</h2><div className="mt-7"><CTA href="/contact" className="bg-[#D4AF37] text-[#0F3F1A]">تواصل معنا</CTA></div></section></Shell>;
}

function StartYourStore(){
 const faqs=[['هل متجر بيت الريف هو صفحة مزود الخدمة العامة؟','لا. صفحة المزود العامة للاكتشاف والمعلومات، بينما المتجر واجهة تجارية للعناصر المنشورة وسياسات التعامل.'],['هل يمكن إضافة منتجات وخدمات وعروض؟','نعم عندما تسمح الخطة والصلاحيات بذلك وبحسب الحصة المفعلة.'],['هل عدد العناصر غير محدود؟','لا. الحصة والخطة والصلاحيات تحدد عدد العناصر المتاحة للنشر.'],['ما السياسات التي يجب أن تظهر؟','السياسات المناسبة لطبيعة النشاط مثل الشحن والتوصيل والاسترجاع والضمان عند انطباقها.']];
 return <Shell><Head><title>أنشئ متجرك على بيت الريف | بيت الريف</title><meta name="description" content="فعّل متجر شركتك على بيت الريف ونظّم المنتجات والخدمات والعروض وسياسات الشحن والتوصيل والاسترجاع والضمان وفق خطتك."/><link rel="canonical" href="https://bietalreef.ae/start-your-store"/></Head>
 <section className="bg-gradient-to-b from-purple-50 to-white py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-2 lg:items-center"><div><span className="rounded-full bg-purple-100 px-4 py-2 text-sm font-black text-purple-800">متجرك داخل سوق بيت الريف</span><h1 className="mt-6 text-4xl font-black leading-tight text-[#34164F] md:text-6xl">أنشئ متجرك على بيت الريف</h1><p className="mt-6 text-lg leading-9 text-gray-600">واجهة تجارية مرتبطة بهوية شركتك لعرض المنتجات والخدمات والعروض مع سياسات شراء وتعامل واضحة.</p><div className="mt-8"><CTA href="/join-biet-alreef" className="bg-[#5B2A86] text-white">فعّل حساب شركتك</CTA></div></div><div className="rounded-[2rem] bg-[#34164F] p-9 text-white"><Store className="h-12 w-12 text-[#F3D46B]"/><h2 className="mt-5 text-3xl font-black">متجر واضح للعميل</h2><p className="mt-4 leading-8 text-white/75">يجمع المتجر العناصر والسياسات ومعلومات التعامل في واجهة تجارية مستقلة داخل السوق.</p></div></div></section>
 <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-black">ما الذي يتضمنه المتجر؟</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[[PackageCheck,'المنتجات والخدمات والعروض','العناصر المنشورة وفق الخطة والحصة.'],[Truck,'الشحن والتوصيل','سياسات واضحة عندما تنطبق.'],[Undo2,'الاسترجاع','شروط الاسترجاع والاستبدال عند انطباقها.'],[ShieldCheck,'الضمان','معلومات الضمان ومدته ونطاقه.'],[FileText,'سياسات المتجر','الشروط المهمة للشراء والتعامل.'],[BadgeCheck,'هوية النشاط','ربط المتجر بالشركة دون تحويله إلى صفحة مزود عامة.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-purple-100 bg-white p-7"><I className="h-8 w-8 text-[#5B2A86]"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
 <section className="bg-white py-16"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">كيف تجهز متجرك؟</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','فعّل الحساب'],['02','أكمل البيانات والسياسات'],['03','أضف العناصر ضمن الحصة'],['04','أدر النشر والتحديث']].map(([n,t])=><div key={n} className="rounded-3xl bg-purple-50 p-6"><span className="text-3xl font-black text-purple-700">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section><FAQ items={faqs} title="الأسئلة الشائعة حول متجر بيت الريف"/><section className="bg-[#34164F] py-16 text-center text-white"><h2 className="text-3xl font-black">جهّز متجرك ليكون واجهة أعمال حقيقية</h2><div className="mt-7"><CTA href="/join-biet-alreef" className="bg-[#D4AF37] text-[#34164F]">ضم شركتك الآن</CTA></div></section></Shell>;
}

function BusinessPlans(){
 const faqs=[['ما قيمة الخطة الشهرية الحالية؟','العرض الحالي المعلن للخطة الشهرية هو 500 درهم وفق شروط ومزايا الخطة المعتمدة.'],['هل توجد مزايا للاشتراك السنوي؟','قد تتضمن الاشتراكات السنوية المؤهلة مزايا Google للأعمال ودومين الشركة وفق شروط الباقة المحددة عند الاشتراك.'],['هل يمكن طلب استرداد؟','تطبق سياسة الاسترداد المعلنة خلال 30 يومًا وفق الشروط والاستثناءات والخدمات التي تم تفعيلها.'],['هل توجد أسعار 299 أو 799 درهم؟','لا تعتمد هذه الصفحة أي أسعار غير معتمدة ضمن خطط بيت الريف الحالية.']];
 return <Shell><Head><title>خطط الأعمال والاشتراكات | بيت الريف</title><meta name="description" content="راجع خطط بيت الريف للأعمال والمزايا والصلاحيات والحصص والاشتراك الشهري الحالي ومزايا الاشتراك السنوي المؤهل."/><link rel="canonical" href="https://bietalreef.ae/business-plans"/></Head>
 <section className="bg-gradient-to-b from-orange-50 to-white py-20 text-center"><div className="mx-auto max-w-7xl px-4"><span className="rounded-full bg-orange-100 px-4 py-2 text-sm font-black text-orange-800">خطط واضحة بدون أسعار غير معتمدة</span><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-black leading-tight text-[#5B3517] md:text-6xl">خطط الأعمال والاشتراكات</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-gray-600">اختر الخطة بحسب الأدوات والعناصر والحصص والصلاحيات التي تحتاجها شركتك.</p></div></section>
 <section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-7 lg:grid-cols-[1fr_.8fr]"><article className="rounded-[2rem] border-2 border-[#D4AF37] bg-white p-9"><WalletCards className="h-9 w-9 text-[#A95B19]"/><h2 className="mt-5 text-3xl font-black">الخطة الشهرية الحالية</h2><div className="mt-5"><span className="text-5xl font-black text-[#0F3F1A]">500</span><span className="mr-2 font-bold text-gray-600">درهم / شهر</span></div><p className="mt-5 leading-8 text-gray-600">تحدد الصلاحيات والحصص والأدوات وفق الخطة المفعلة وحالة الحساب.</p><div className="mt-7"><CTA href="/contact" className="bg-[#0F3F1A] text-white">راجع المزايا قبل التفعيل</CTA></div></article><aside className="rounded-[2rem] bg-[#0F3F1A] p-9 text-white"><BriefcaseBusiness className="h-10 w-10 text-[#F3D46B]"/><h2 className="mt-5 text-2xl font-black">ماذا تحدد الخطة؟</h2><div className="mt-6 space-y-3">{['الأدوات المتاحة','حصص العناصر','صلاحيات النشر والإدارة','الخدمات والمزايا المشمولة'].map(x=><div key={x} className="rounded-2xl bg-white/10 p-4 font-bold">{x}</div>)}</div></aside></div></section>
 <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-4"><h2 className="text-3xl font-black">مزايا الاشتراك السنوي المؤهل</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{[[Globe2,'Google للأعمال','قد تتضمن الباقات المؤهلة مزايا Google للأعمال وفق الشروط.'],[BriefcaseBusiness,'دومين الشركة','قد يكون دومين الشركة ضمن مزايا الباقة المؤهلة.'],[FileText,'سياسة استرداد','فترة الاسترداد المعلنة 30 يومًا وفق الشروط والاستثناءات.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFFDF8] p-7"><I className="h-8 w-8"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></div></section><FAQ items={faqs} title="الأسئلة الشائعة حول خطط الأعمال"/><section className="bg-[#5B3517] py-16 text-center text-white"><h2 className="text-3xl font-black">اختر الخطة بعد فهم المزايا والصلاحيات</h2><div className="mt-7"><CTA href="/contact" className="bg-[#D4AF37] text-[#5B3517]">تحدث مع خدمة العملاء</CTA></div></section></Shell>;
}

const ROUTES={
 '/platform-for-business': PlatformForBusiness,
 '/join-provider': JoinProvider,
 '/business-solutions': BusinessSolutions,
 '/start-your-store': StartYourStore,
 '/business-plans': BusinessPlans,
};

export function getPlatformLanding(path){ return ROUTES[path] || null; }
