import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import FAQ from '../../components/FAQ';
import { ArrowRight, Bot, FileText, PackageSearch, BriefcaseBusiness, ShieldCheck, Sparkles } from 'lucide-react';

const faqs=[['What is Weyaak?','Weyaak is an intelligent business assistant from Biet Al Reef, designed to help with tasks connected to company account data and platform workflows.'],['Is Weyaak a general chatbot?','No. Its core role is to work inside Biet Al Reef using account data and permissions.'],['How does it help companies?','It helps organise information, draft content, prepare product, service and offer data, documents and guidance within work journeys according to permissions.'],['Does it make decisions instead of the business owner?','No. It helps with understanding, organisation and preparation, while final decisions and sensitive actions remain with the user and authorised parties.']];

export default function WeyaakAIEnglish(){return <><Head><title>Weyaak – AI from Biet Al Reef | Intelligent Business Assistant</title><meta name="description" content="Meet Weyaak, the intelligent business assistant inside Biet Al Reef that works with company account context to help with content, listings, documents and workflows."/><link rel="canonical" href="https://bietalreef.ae/en/weyaak-ai"/></Head><div dir="ltr" className="min-h-screen bg-[#F7FBF8]"><Navbar locale="en"/><main>
<section className="relative overflow-hidden bg-[#062F22] py-20 text-white md:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(52,211,153,.2),transparent_32%)]"/><div className="relative mx-auto max-w-7xl px-4 text-center"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 font-black text-emerald-200"><Sparkles className="h-5 w-5"/>Weyaak | AI from Biet Al Reef</span><h1 className="mx-auto mt-6 max-w-5xl text-4xl font-black leading-tight md:text-6xl">An intelligent business assistant working inside your company context</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-white/80">Weyaak is not a separate general chatbot. It is an assistant inside the Biet Al Reef ecosystem that helps with content, listings, documents, information and business workflows according to account data, plan and permissions.</p><Link href="/en/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">Learn about Weyaak inside Biet Al Reef <ArrowRight className="h-5 w-5"/></Link></div></section>
<section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[[BriefcaseBusiness,'Understands business context','Company identity, specialties, areas and data available to the account.'],[PackageSearch,'Listings and store','Helps prepare product, service and offer information within the available path.'],[FileText,'Documents and content','Organises and drafts business information, content and documents.'],[ShieldCheck,'Within permissions','Capabilities depend on account status, plan, permissions and available data.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-emerald-100 bg-white p-7 shadow-sm"><I className="h-8 w-8 text-[#087A57]"/><h2 className="mt-4 text-xl font-black">{t}</h2><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
<section className="bg-white py-16"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">How does Weyaak work inside the account?</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','Understands your account context'],['02','You define the required task'],['03','Helps inside the right workflow'],['04','You review the result and continue']].map(([n,t])=><div key={n} className="rounded-3xl bg-emerald-50 p-6"><span className="text-3xl font-black text-emerald-700">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] bg-[#062F22] p-8 text-white"><Bot className="h-9 w-9 text-emerald-200"/><h2 className="mt-5 text-2xl font-black">AI inside a real business environment</h2><p className="mt-4 leading-8 text-white/75">Weyaak's core value comes from its connection to company context and business workflows, not from providing a general chat without context.</p></article><article className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><h2 className="text-2xl font-black">The final decision belongs to the user</h2><p className="mt-4 leading-8 text-gray-700">Weyaak helps with understanding, organisation and preparation, but it does not replace the account owner or authorised party in sensitive or final decisions.</p></article></div></section>
<FAQ items={faqs} title="Frequently asked questions about Weyaak"/>
<section className="bg-[#062F22] py-16 text-white"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black">Weyaak inside the Biet Al Reef ecosystem</h2><Link href="/en/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">Talk to the Biet Al Reef team <ArrowRight className="h-5 w-5"/></Link></div></section>
</main><Footer locale="en"/></div></>}
