import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import FAQ from '../../components/FAQ';
import { ArrowRight, Bot, FileText, PackageSearch, BriefcaseBusiness, ShieldCheck, Sparkles, Megaphone, ShoppingBag, MapPinned, Mail, Cloud, CheckCircle2 } from 'lucide-react';

const faqs=[
  ['What is Weyaak?','Weyaak is an intelligent operational business assistant from Biet Al Reef that works inside the context of the company account, its data, workflows and available permissions.'],
  ['Is Weyaak a general chatbot?','No. Its core role is not to provide detached general answers, but to help the business inside real workflows and prepare content, data and next steps connected to enabled paths.'],
  ['Do I need technical knowledge to connect my products to Google Shopping through Weyaak?','No technical expertise is required. Weyaak can help organise and draft product data stored in your account and prepare it for available publishing and integration paths before review and synchronisation.'],
  ['How does Weyaak handle company data when using Google services?','Weyaak works according to account context, permissions and enabled integrations inside Biet Al Reef. Sensitive or final actions are only performed through authorised account workflows.'],
  ['Is Biet Al Reef listed in Google Cloud Partner Finder?','Yes. Biet Al Reef has a public official profile in Google Cloud Partner Finder showing the company and its technical focus areas in the UAE, without claiming a Tier that is not displayed publicly.'],
  ['Does Weyaak make decisions instead of the business owner?','No. It helps with understanding, organisation, preparation and automation within permissions, while final decisions and sensitive actions remain with the user or authorised party.']
];

const faqSchema={
  '@context':'https://schema.org',
  '@type':'FAQPage',
  mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))
};

const googleServices=[
  {icon:Megaphone,title:'Weyaak + Google Ads',subtitle:'From business context to clearer campaign ideas',items:['Analyse your business and service information to draft initial ad copy that is more relevant to the target market.','Extract competitive strengths from products and services and turn them into campaign ideas ready for review before publishing.']},
  {icon:ShoppingBag,title:'Weyaak + Google Shopping',subtitle:'Prepare product data for commercial publishing',items:['Organise product data, specifications and prices to simplify preparation of feeds for the Google Merchant Center path.','Improve product titles and descriptions for clearer search and shopping visibility while keeping review before synchronisation.']},
  {icon:MapPinned,title:'Weyaak + Google Maps APIs',subtitle:'Locations, coverage and routes in business context',items:['Organise location, service-area and delivery data to simplify display and map integration when the appropriate path is available.','Help field teams prepare branch data, route information and location-based logistics requirements.']},
  {icon:Mail,title:'Weyaak + Google Workspace',subtitle:'Messages, files and schedules in one business environment',items:['Draft follow-up emails, quotations and professional correspondence using account context and company business email.','Help organise and summarise available files and coordinate tasks and appointments through Drive and Calendar paths when integrations are enabled.']},
  {icon:Cloud,title:'Weyaak + Google Cloud',subtitle:'Operational intelligence on scalable cloud infrastructure',items:['Use Google Cloud services in technical paths enabled for the account, including applications, data, AI and integrations.','Keep execution separated by permissions and service scope while preserving final control for the account and authorised parties.']}
];

const comparison=[
  ['Data context','General answers without real knowledge of your products or service areas','Works with account identity, listings, areas and available data according to permissions'],
  ['Service connections','Each platform requires separate setup and manual workflows','Unifies work inside Biet Al Reef and prepares data for enabled Google paths'],
  ['Control and execution','The AI tool may be detached from organisation permissions and workflows','Execution depends on account status, plan, permissions and review before sensitive actions'],
  ['Technical transparency','Broad claims about partnerships or security','Biet Al Reef is officially listed in Google Cloud Partner Finder without claiming an undisclosed Tier']
];

export default function WeyaakAIEnglish(){return <><Head>
<title>Weyaak | Embedded AI for Business & Google Services | Biet Al Reef</title>
<meta name="description" content="Embedded AI for your business environment. Weyaak connects business workflows with Google Ads, Google Shopping, Maps, Workspace and Google Cloud through controlled account context."/>
<meta name="keywords" content="Weyaak Biet Al Reef, AI for business UAE, Google Workspace UAE, Google Ads, Google Shopping, Google Cloud Partner Finder"/>
<meta name="robots" content="index, follow, max-image-preview:large"/>
<link rel="canonical" href="https://bietalreef.ae/en/weyaak-ai"/>
<meta property="og:title" content="Weyaak | Embedded AI for Business & Google Services | Biet Al Reef"/>
<meta property="og:description" content="Weyaak works inside your company context and connects content and data preparation with Google business workflows according to available permissions."/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://bietalreef.ae/en/weyaak-ai"/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
</Head><div dir="ltr" className="min-h-screen bg-[#F7FBF8]"><Navbar locale="en"/><main>

<section className="relative overflow-hidden bg-[#062F22] py-20 text-white md:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(52,211,153,.2),transparent_32%)]"/><div className="relative mx-auto max-w-7xl px-4"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 font-black text-emerald-200"><Sparkles className="h-5 w-5"/>Weyaak | Operational AI from Biet Al Reef</span><h1 className="mt-6 max-w-5xl text-4xl font-black leading-tight md:text-6xl">Weyaak: AI embedded in your business context and Google ecosystem</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-white/80">Not a general-response chatbot. Weyaak is an intelligent operational assistant working inside your Biet Al Reef company account, helping connect documents, messages, product data and business workflows with Google services such as Shopping, Ads, Maps, Workspace and Google Cloud according to enabled permissions and integrations.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="https://play.google.com/store/apps/details?id=ae.bietalreef.app" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">Download the app and talk to Weyaak <ArrowRight className="h-5 w-5"/></a><a href="#google-services" className="inline-flex items-center justify-center rounded-2xl border border-white/25 px-8 py-4 font-black">Explore Google integrations</a></div></div><div className="rounded-[2rem] border border-white/10 bg-white/10 p-8 backdrop-blur"><Bot className="h-12 w-12 text-emerald-200"/><h2 className="mt-5 text-3xl font-black">From information to action inside the same business environment</h2><p className="mt-4 leading-8 text-white/75">Weyaak uses account context, plan, permissions and available listings to reduce friction between content, store, documents and Google workflows instead of operating as a tool detached from your company.</p></div></div></div></section>

<section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[[BriefcaseBusiness,'Understands business context','Company identity, specialties, areas and data available to the account.'],[PackageSearch,'Listings and store','Helps prepare product, service and offer information within the available path.'],[FileText,'Documents and content','Organises and drafts business information, content and documents.'],[ShieldCheck,'Within permissions','Capabilities depend on account status, plan, permissions, data and enabled integrations.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-emerald-100 bg-white p-7 shadow-sm"><I className="h-8 w-8 text-[#087A57]"/><h2 className="mt-4 text-xl font-black">{t}</h2><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>

<section id="google-services" className="bg-white py-16 md:py-20"><div className="mx-auto max-w-7xl px-4"><div className="mb-10 max-w-4xl"><p className="font-black text-emerald-700">Google ecosystem inside the workflow</p><h2 className="mt-2 text-3xl font-black md:text-4xl">How Weyaak works with different Google services</h2><p className="mt-4 leading-8 text-gray-600">Open each service to see how Weyaak can help inside your account context, while execution remains tied to enabled integrations and permissions.</p></div><div className="grid gap-5 lg:grid-cols-2">{googleServices.map(({icon:Icon,title,subtitle,items})=><details key={title} className="group rounded-[2rem] border border-emerald-100 bg-[#F8FCFA] p-0 shadow-sm open:bg-white"><summary className="flex cursor-pointer list-none items-center gap-4 p-6"><div className="rounded-2xl bg-emerald-100 p-3 text-emerald-800"><Icon className="h-7 w-7"/></div><div className="flex-1"><h3 className="text-xl font-black">{title}</h3><p className="mt-1 text-sm font-bold text-gray-500">{subtitle}</p></div><span className="text-2xl font-black text-emerald-700 group-open:rotate-45">+</span></summary><div className="space-y-3 border-t border-emerald-100 px-6 pb-6 pt-5">{items.map(x=><p key={x} className="flex items-start gap-3 leading-8 text-gray-700"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-emerald-600"/>{x}</p>)}</div></details>)}</div></div></section>

<section className="mx-auto max-w-7xl px-4 py-16 md:py-20"><div className="mb-10 max-w-4xl"><p className="font-black text-emerald-700">The real difference</p><h2 className="mt-2 text-3xl font-black md:text-4xl">Weyaak inside a real business environment, not a separate AI tool</h2></div><div className="overflow-x-auto rounded-[2rem] border border-emerald-100 bg-white shadow-sm"><table className="min-w-[880px] w-full text-left"><thead className="bg-[#062F22] text-white"><tr><th className="p-5 text-lg">Comparison</th><th className="p-5 text-lg">General AI tools</th><th className="p-5 text-lg">Weyaak through Biet Al Reef</th></tr></thead><tbody>{comparison.map(([a,b,c],i)=><tr key={a} className={i%2?'bg-emerald-50/40':'bg-white'}><td className="p-5 align-top font-black text-[#062F22]">{a}</td><td className="p-5 align-top leading-8 text-gray-600">{b}</td><td className="p-5 align-top leading-8 text-gray-700">{c}</td></tr>)}</tbody></table></div><div className="mt-6 flex flex-wrap gap-3"><Link href="/en/google-cloud-biet-alreef" className="inline-flex items-center gap-2 rounded-2xl bg-[#062F22] px-6 py-3 font-black text-white">Google Cloud with Biet Al Reef <ArrowRight className="h-4 w-4"/></Link><Link href="/en/google-workspace-biet-alreef" className="inline-flex items-center gap-2 rounded-2xl border border-emerald-200 bg-white px-6 py-3 font-black text-[#062F22]">Google Workspace with Biet Al Reef <ArrowRight className="h-4 w-4"/></Link></div></section>

<section className="bg-[#062F22] py-16 text-white"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">How does Weyaak work inside the account?</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','Understands your account context'],['02','You define the required task'],['03','Prepares data inside the right workflow'],['04','You review the result and continue']].map(([n,t])=><div key={n} className="rounded-3xl bg-white/10 p-6"><span className="text-3xl font-black text-emerald-200">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section>

<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] bg-white p-8 shadow-sm"><Bot className="h-9 w-9 text-emerald-700"/><h2 className="mt-5 text-2xl font-black">Automation and assistance inside company context</h2><p className="mt-4 leading-8 text-gray-600">Weyaak's core value comes from its connection to company context, workflows, listings, data and enabled integrations rather than providing a general chat without context.</p></article><article className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><h2 className="text-2xl font-black">The final decision belongs to the user</h2><p className="mt-4 leading-8 text-gray-700">Weyaak helps with understanding, organisation, preparation and automation within permissions, but it does not replace the account owner or authorised party in sensitive or final decisions.</p></article></div></section>

<FAQ items={faqs} title="Frequently asked questions about Weyaak and Google services"/>
<section className="bg-[#062F22] py-16 text-white"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black">Weyaak inside your business ecosystem, not beside it</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-white/75">Start from your account, data and workflows, then enable the integrations and services that fit your company needs.</p><a href="https://play.google.com/store/apps/details?id=ae.bietalreef.app" target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">Download the app and talk to Weyaak <ArrowRight className="h-5 w-5"/></a></div></section>
</main><Footer locale="en"/></div></>}
