import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FAQ from '../components/FAQ';
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, FileText, Globe2, ShieldCheck, WalletCards } from 'lucide-react';

const faqs=[['ما قيمة الخطة الشهرية الحالية؟','العرض الحالي المعلن للخطة الشهرية هو 500 درهم وفق شروط ومزايا الخطة المعتمدة.'],['هل توجد مزايا للاشتراك السنوي؟','قد تتضمن الاشتراكات السنوية المؤهلة مزايا Google للأعمال ودومين الشركة وفق شروط الباقة المحددة عند الاشتراك.'],['هل يمكن طلب استرداد؟','تطبق سياسة الاسترداد المعلنة خلال 30 يومًا وفق الشروط والاستثناءات والخدمات التي تم تفعيلها.'],['هل توجد أسعار 299 أو 799 درهم؟','لا تعتمد هذه الصفحة أي أسعار غير معتمدة ضمن خطط بيت الريف الحالية.']];

export default function BusinessPlans(){return <><Head><title>خطط الأعمال والاشتراكات | بيت الريف</title><meta name="description" content="راجع خطط بيت الريف للأعمال والمزايا والصلاحيات والحصص والاشتراك الشهري الحالي ومزايا الاشتراك السنوي المؤهل."/><link rel="canonical" href="https://bietalreef.ae/business-plans"/></Head><div dir="rtl" className="min-h-screen bg-[#FFFCF7]"><Navbar/><main>
<section className="relative overflow-hidden bg-gradient-to-b from-orange-50 to-white py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 text-center"><span className="inline-flex rounded-full bg-orange-100 px-4 py-2 text-sm font-black text-orange-800">خطط واضحة بدون أسعار غير معتمدة</span><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-black leading-tight text-[#5B3517] md:text-6xl">خطط الأعمال والاشتراكات</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-gray-600">اختر الخطة بحسب طريقة استخدام شركتك لبيت الريف، وعدد الأدوات والعناصر والحصص والصلاحيات التي تحتاجها، مع توضيح المزايا قبل التفعيل.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#A95B19] px-7 py-4 font-black text-white">تحدث مع خدمة العملاء <ArrowLeft className="h-5 w-5"/></Link><a href="#plans" className="rounded-2xl border border-orange-300 px-7 py-4 font-black text-orange-800">راجع الخطة الحالية</a></div></div></section>
<section id="plans" className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-7 lg:grid-cols-[1fr_.8fr]"><article className="rounded-[2rem] border-2 border-[#D4AF37] bg-white p-8 shadow-lg md:p-10"><div className="flex items-center gap-3"><WalletCards className="h-9 w-9 text-[#A95B19]"/><span className="rounded-full bg-orange-100 px-3 py-1 text-sm font-black text-orange-800">العرض الحالي</span></div><h2 className="mt-6 text-3xl font-black">الخطة الشهرية</h2><div className="mt-5 flex items-end gap-2"><span className="text-5xl font-black text-[#0F3F1A]">500</span><span className="pb-2 font-bold text-gray-600">درهم / شهر</span></div><p className="mt-5 leading-8 text-gray-600">تحدد الصلاحيات والحصص والأدوات المتاحة وفق الخطة المفعلة وحالة الحساب. لا تعتمد الصفحة أي أسعار أخرى غير معتمدة.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-[#0F3F1A] px-7 py-4 font-black text-white">راجع المزايا قبل التفعيل <ArrowLeft className="h-5 w-5"/></Link></article><aside className="rounded-[2rem] bg-[#0F3F1A] p-8 text-white md:p-10"><BriefcaseBusiness className="h-10 w-10 text-[#F3D46B]"/><h2 className="mt-5 text-2xl font-black">ماذا تحدد الخطة؟</h2><div className="mt-6 space-y-4">{['الأدوات المتاحة للحساب','حصص المنتجات والخدمات والعروض والمشاريع','صلاحيات النشر والإدارة','المزايا والخدمات المشمولة'].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4"><BadgeCheck className="h-5 w-5 text-[#F3D46B]"/><span className="font-bold">{x}</span></div>)}</div></aside></div></section>
<section className="bg-white py-16"><div className="mx-auto max-w-7xl px-4"><div className="mb-10"><p className="font-black text-[#B8922B]">مزايا الاشتراك السنوي المؤهل</p><h2 className="mt-2 text-3xl font-black">مزايا إضافية بحسب شروط الباقة</h2></div><div className="grid gap-6 md:grid-cols-3">{[[Globe2,'Google للأعمال','قد تتضمن الباقات السنوية المؤهلة مزايا Google للأعمال وفق الشروط المحددة.'],[BriefcaseBusiness,'دومين الشركة','قد يكون دومين الشركة ضمن مزايا الاشتراك السنوي المؤهل وفق شروط الباقة.'],[FileText,'سياسة استرداد','فترة الاسترداد المعلنة 30 يومًا وفق الشروط والاستثناءات والخدمات المفعلة.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFFDF8] p-7"><I className="h-8 w-8 text-[#0F3F1A]"/><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><h2 className="text-3xl font-black">كيف تختار خطتك؟</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','حدد احتياج شركتك'],['02','راجع الحصص والصلاحيات'],['03','اختر مدة الاشتراك'],['04','فعّل الحساب']].map(([n,t])=><div key={n} className="rounded-3xl border border-orange-100 bg-orange-50 p-6"><span className="text-3xl font-black text-orange-700">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></section>
<section className="mx-auto max-w-6xl px-4 pb-16"><div className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><ShieldCheck className="h-8 w-8 text-[#0F3F1A]"/><h2 className="mt-4 text-2xl font-black">التفعيل حسب الشروط الفعلية</h2><p className="mt-4 leading-8 text-gray-700">أي ميزة مجانية أو مضمنة في اشتراك سنوي هي عرض من بيت الريف وتخضع لشروط الباقة. لا يتم تقديمها على أنها عرض مجاني عام من Google.</p></div></section>
<FAQ items={faqs} title="الأسئلة الشائعة حول خطط الأعمال"/>
<section className="bg-[#5B3517] py-16 text-white"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black">اختر الخطة بعد فهم المزايا والصلاحيات</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-[#D4AF37] px-8 py-4 font-black text-[#5B3517]">تحدث مع خدمة العملاء <ArrowLeft className="h-5 w-5"/></Link></div></section>
</main><Footer/></div></>}
