import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { ArrowLeft, BadgeCheck, Gift, Globe2, Sparkles, Store, WalletCards } from 'lucide-react';

const plans=[
{name:'الخطة المجانية',badge:'مجانية',monthly:'0 AED',annual:'بدون تاريخ تجديد',features:['حساب شخصي موثق داخل تطبيق بيت الريف','فتح الملف الشخصي والخطة المجانية','التصفح واستخدام الأدوات المتاحة وفق النظام','لا تشمل حصة نشر ضمن الخطة']},
{name:'الحضور الرقمي',badge:'4 بطاقات',monthly:'300 AED',annual:'2,700 AED',saving:'خصم سنوي 25% — وفر 900 درهم سنويًا',gift:'هدية: باقة النشر العام – 4 بطاقات مع الاشتراك السنوي',features:['4 منتجات + 4 خدمات + 4 عروض + 4 مستندات','ربط Google Drive وGoogle Sheets','مساعد أعمال وياك','النشر داخل تطبيق بيت الريف وفق صلاحيات الخطة']},
{name:'الحضور الاحترافي',badge:'10 بطاقات',monthly:'500 AED',annual:'4,500 AED',saving:'خصم سنوي 25% — وفر 1,500 درهم سنويًا',gift:'هدية: باقة النشر العام للأعمال – 10 بطاقات مع الاشتراك السنوي',featured:true,features:['10 منتجات + 10 خدمات + 10 عروض + 10 مستندات','مساحة Google Cloud منفصلة وفق الخطة','Google Workspace ودومين ضمن مزايا الاشتراك السنوي المؤهل','مساعد أعمال وياك بصلاحيات الخطة']}
];
const packages=[
{name:'باقة النشر العام – 4 بطاقات',icon:Globe2,price:'750 AED',benefit:'تُفتح مجانًا مع الاشتراك السنوي لخطة الحضور الرقمي',features:['نشر 4 بطاقات مؤهلة في سوق بيت الريف','نشر 4 منتجات شهريًا في Google Shopping','ملف تاجر مستقل وحضور ضمن دليل المتاجر في سوق بيت الريف','صفحة هبوط كاملة في منصة بيت الريف']},
{name:'باقة النشر العام للأعمال – 10 بطاقات',icon:Store,price:'1,500 AED',benefit:'تُفتح مجانًا مع الاشتراك السنوي لخطة الحضور الاحترافي',features:['نشر 10 بطاقات مؤهلة في سوق بيت الريف','نشر حتى 10 منتجات شهريًا في Google Shopping','ملف تاجر مستقل وحضور ضمن دليل المتاجر في سوق بيت الريف','صفحة هبوط كاملة في منصة بيت الريف']}
];
const comparisonCards=[
{name:'الخطة المجانية',badge:'0 درهم',lines:['حساب شخصي موثق','ملف شخصي داخل التطبيق','تصفح واستخدام الأدوات المتاحة','بدون حصة نشر ضمن الخطة']},
{name:'الحضور الرقمي',badge:'300 شهريًا • 2,700 سنويًا',lines:['4 منتجات + 4 خدمات + 4 عروض + 4 مستندات','Google Drive + Google Sheets','مساعد أعمال وياك','النشر داخل التطبيق: 4 من كل نوع','السنوي: باقة النشر العام 4 بطاقات هدية']},
{name:'الحضور الاحترافي',badge:'500 شهريًا • 4,500 سنويًا',featured:true,lines:['10 منتجات + 10 خدمات + 10 عروض + 10 مستندات','Google Drive + Google Sheets','مساحة Google Cloud منفصلة وفق الخطة','Google Workspace + دومين ضمن مزايا السنوي المؤهل','مساعد أعمال وياك بصلاحيات الخطة','النشر داخل التطبيق: 10 من كل نوع','السنوي: باقة النشر العام للأعمال 10 بطاقات هدية']},
{name:'الشركات والمؤسسات',badge:'خطة مخصصة',lines:['خطة تُحدد حسب احتياجات الشركة أو المؤسسة','الحصص والصلاحيات حسب متطلبات العمل','حلول Google والأدوات حسب الاتفاق','مساعد أعمال وياك وفق نطاق الخطة','النشر والتواجد الرقمي حسب الاحتياج','التواصل مع بيت الريف لإعداد الخطة']},
{name:'النشر العام – 4 بطاقات',badge:'750 درهم',lines:['4 بطاقات مؤهلة في سوق بيت الريف','4 منتجات شهريًا في Google Shopping','ملف تاجر مستقل وحضور ضمن دليل المتاجر في سوق بيت الريف','صفحة هبوط كاملة في منصة بيت الريف','مجانية مع السنوي للحضور الرقمي']},
{name:'النشر العام للأعمال – 10 بطاقات',badge:'1,500 درهم',lines:['10 بطاقات مؤهلة في سوق بيت الريف','حتى 10 منتجات شهريًا في Google Shopping','ملف تاجر مستقل وحضور ضمن دليل المتاجر في سوق بيت الريف','صفحة هبوط كاملة في منصة بيت الريف','مجانية مع السنوي للحضور الاحترافي']}
];
export default function PricingPage(){return <><Head><title>الأسعار والخطط | بيت الريف</title><meta name="description" content="خطط وأسعار بيت الريف مع مقارنة واضحة بين الخطة المجانية والحضور الرقمي والحضور الاحترافي وخطة الشركات والمؤسسات المخصصة وباقات النشر العام."/><link rel="canonical" href="https://bietalreef.ae/pricing"/></Head><div dir="rtl" className="min-h-screen bg-[#FFFCF7] text-gray-900"><Navbar/><main>
<section className="bg-gradient-to-b from-[#123F1D] to-[#062D17] py-16 text-white md:py-24"><div className="mx-auto max-w-7xl px-4 text-center"><span className="inline-flex items-center gap-2 rounded-full border border-[#D4AF37]/50 bg-[#D4AF37]/15 px-4 py-2 text-sm font-black text-[#F3D46B]"><Sparkles className="h-4 w-4"/> الأسعار والخطط</span><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-black leading-tight md:text-6xl">خطط وأسعار بيت الريف</h1><p className="mx-auto mt-6 max-w-4xl text-lg leading-9 text-white/85">اختر الخطة بحسب طريقة استخدام شركتك لبيت الريف، وعدد الأدوات والعناصر والحصص والصلاحيات التي تحتاجها، مع توضيح المزايا قبل التفعيل.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="#plans" className="inline-flex items-center gap-2 rounded-2xl bg-[#D4AF37] px-7 py-4 font-black text-[#0F3F1A]">استعرض الخطط <ArrowLeft className="h-5 w-5"/></a><a href="#compare" className="inline-flex items-center rounded-2xl border border-white/30 bg-white/10 px-7 py-4 font-black">مقارنة سريعة بين الخطط</a></div></div></section>
<section id="plans" className="mx-auto max-w-7xl px-4 py-16 md:py-20"><p className="font-black text-[#B8922B]">الاشتراك داخل تطبيق بيت الريف</p><h2 className="mt-2 text-3xl font-black md:text-4xl">الخطط الأساسية</h2><p className="mt-3 max-w-4xl leading-8 text-gray-600">الاشتراك يحدد الحصص والصلاحيات والأدوات داخل التطبيق، بينما باقات النشر العام مستقلة عند شرائها منفردة.</p><div className="mt-10 grid gap-6 lg:grid-cols-3">{plans.map(p=><article key={p.name} className={`relative rounded-[2rem] border bg-white p-7 shadow-sm ${p.featured?'border-2 border-[#D4AF37] shadow-lg':'border-[#E6DCC8]'}`}>{p.featured&&<span className="absolute -top-3 left-6 rounded-full bg-[#D4AF37] px-4 py-1 text-sm font-black text-[#0F3F1A]">الأكثر شمولًا</span>}<div className="flex items-center justify-between"><WalletCards className="h-9 w-9 text-[#0F3F1A]"/><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-black text-emerald-700">{p.badge}</span></div><h3 className="mt-6 text-2xl font-black">{p.name}</h3><div className="mt-5 text-4xl font-black text-[#0F3F1A]">{p.monthly}</div><p className="mt-1 text-sm font-bold text-gray-500">{p.monthly!=='0 AED'?'شهريًا':''}</p><div className="mt-4 rounded-2xl bg-[#FFF8E5] p-4"><strong className="text-lg text-[#0F3F1A]">{p.annual}</strong>{p.saving&&<p className="mt-1 text-sm font-bold text-[#A95B19]">{p.saving}</p>}{p.gift&&<p className="mt-2 text-sm font-black text-emerald-700">{p.gift}</p>}</div><div className="mt-6 space-y-3">{p.features.map(f=><div key={f} className="flex items-start gap-3"><BadgeCheck className="mt-1 h-5 w-5 shrink-0 text-emerald-600"/><span className="leading-7 text-gray-700">{f}</span></div>)}</div><Link href="/contact" className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0F3F1A] px-6 py-4 font-black text-white">اختيار الخطة <ArrowLeft className="h-5 w-5"/></Link></article>)}</div></section>
<section id="compare" className="border-y border-[#E9E0D0] bg-[#F7F2E8] py-16 md:py-20"><div className="mx-auto max-w-[1500px] px-4"><div className="text-center"><p className="font-black text-[#B8922B]">مقارنة سريعة</p><h2 className="mt-2 text-3xl font-black md:text-4xl">كل باقة ومزاياها في مربع واحد</h2><p className="mx-auto mt-3 max-w-3xl leading-8 text-gray-600">شاهد السعر وما تشمله كل باقة كاملة دون التنقل بين صفوف مقارنة طويلة.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{comparisonCards.map(c=><article key={c.name} className={`flex h-full flex-col rounded-[2rem] border p-5 shadow-sm ${c.featured?'border-2 border-[#D4AF37] bg-[#0F3F1A] text-white':'border-[#DED3BE] bg-white'}`}><h3 className="text-lg font-black">{c.name}</h3><div className={`mt-4 rounded-2xl px-3 py-3 text-center text-base font-black ${c.featured?'bg-[#D4AF37] text-[#0F3F1A]':'bg-[#FFF4D2] text-[#0F3F1A]'}`}>{c.badge}</div><div className="mt-5 flex-1 space-y-3">{c.lines.map(line=><div key={line} className="flex items-start gap-2"><BadgeCheck className={`mt-1 h-5 w-5 shrink-0 ${c.featured?'text-[#F3D46B]':'text-emerald-600'}`}/><span className={`text-sm font-bold leading-7 ${c.featured?'text-white/90':'text-gray-700'}`}>{line}</span></div>)}</div></article>)}</div></div></section>
<section className="bg-white py-16 md:py-20"><div className="mx-auto max-w-7xl px-4"><p className="font-black text-[#B8922B]">باقات النشر العام</p><h2 className="mt-2 text-3xl font-black md:text-4xl">النشر خارج التطبيق</h2><p className="mt-3 max-w-4xl leading-8 text-gray-600">هذه الباقات منفصلة عن اشتراك التطبيق عند شرائها منفردة، وتُمنح مع الاشتراك السنوي المناسب حسب الخطة.</p><div className="mt-10 grid gap-6 md:grid-cols-2">{packages.map(pkg=>{const Icon=pkg.icon;return <article key={pkg.name} className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFFDF8] p-8"><Icon className="h-9 w-9 text-[#0F3F1A]"/><h3 className="mt-5 text-2xl font-black">{pkg.name}</h3><div className="mt-5 space-y-3">{pkg.features.map(f=><p key={f} className="flex gap-3"><BadgeCheck className="mt-1 h-5 w-5 shrink-0 text-emerald-600"/>{f}</p>)}</div><div className="mt-6 rounded-2xl border border-[#E6DCC8] bg-white p-5"><p className="text-sm font-bold text-gray-500">سعر الباقة</p><div className="mt-1 text-3xl font-black text-[#0F3F1A]">{pkg.price}</div></div><div className="mt-3 rounded-2xl bg-[#FFF1C2] p-4 font-bold text-[#7B5A00]">{pkg.benefit}</div><Link href="/contact" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0F3F1A] px-6 py-4 font-black text-white">اختيار الباقة <ArrowLeft className="h-5 w-5"/></Link></article>})}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="rounded-[2rem] bg-[#0F3F1A] p-8 text-center text-white md:p-12"><Gift className="mx-auto h-10 w-10 text-[#F3D46B]"/><h2 className="mt-5 text-3xl font-black">تحتاج مساعدة في اختيار الخطة؟</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-white/80">تواصل مع فريق بيت الريف لتحديد الخطة والباقات المناسبة لطريقة عمل شركتك.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-[#D4AF37] px-8 py-4 font-black text-[#0F3F1A]">تواصل معنا <ArrowLeft className="h-5 w-5"/></Link></div></section>
</main><Footer/></div></>}
