import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FAQ from '../components/FAQ';
import { ArrowLeft, ShieldCheck, Clock3, FileCheck2, Headphones, ReceiptText } from 'lucide-react';

const faqs=[['هل الاسترداد مضمون في كل حالة؟','لا. الأهلية تعتمد على شروط الباقة والخدمات أو التكاليف الخارجية التي تم تفعيلها أو تنفيذها.'],['ما مدة طلب الاسترداد المعلنة؟','الفترة المعلنة هي 30 يومًا وفق الشروط والاستثناءات المنشورة عند الاشتراك.'],['كيف أطلب الاسترداد؟','تواصل مع خدمة العملاء وقدم بيانات الحساب والاشتراك ليتم تقييم الأهلية والمبلغ القابل للاسترداد.']];

export default function RefundPolicy(){return <><Head><title>سياسة الاسترداد | بيت الريف</title><meta name="description" content="تعرف على إطار طلب استرداد رسوم اشتراك بيت الريف خلال الفترة المعلنة وشروط الأهلية والخدمات والتكاليف التي قد تؤثر على المبلغ القابل للاسترداد."/><link rel="canonical" href="https://bietalreef.ae/refund-policy"/></Head><div dir="rtl" className="min-h-screen bg-[#FBFCFD]"><Navbar/><main>
<section className="bg-gradient-to-b from-slate-100 to-white py-20 md:py-24"><div className="mx-auto max-w-6xl px-4 text-center"><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-black text-slate-700 shadow-sm"><ShieldCheck className="h-5 w-5"/>السياسات</span><h1 className="mt-6 text-4xl font-black text-[#0F3F1A] md:text-6xl">سياسة الاسترداد</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-gray-600">إطار واضح لطلب استرداد رسوم الاشتراك خلال الفترة المعلنة، مع توضيح أن الأهلية تتأثر بالخدمات والتكاليف التي تم تنفيذها أو تفعيلها فعليًا.</p></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 md:grid-cols-3">{[[Clock3,'30 يومًا','فترة طلب الاسترداد المعلنة وفق الشروط.'],[FileCheck2,'مراجعة الأهلية','تُراجع حالة الحساب والخدمات المفعلة قبل اعتماد الطلب.'],[ReceiptText,'التكاليف المنفذة','قد تُستثنى الخدمات أو التكاليف الخارجية التي تم تنفيذها فعليًا.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm"><I className="h-8 w-8 text-[#0F3F1A]"/><h2 className="mt-4 text-xl font-black">{t}</h2><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
<section className="bg-[#0F3F1A] py-16 text-white"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">كيف تقدم طلب الاسترداد؟</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[['01','تواصل مع الدعم'],['02','قدم بيانات الاشتراك والحساب'],['03','تتم مراجعة الأهلية والمبلغ']].map(([n,t])=><div key={n} className="rounded-3xl bg-white/10 p-6"><span className="text-sm font-black text-[#F3D46B]">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><Headphones className="h-8 w-8 text-[#0F3F1A]"/><h2 className="mt-4 text-2xl font-black">الشروط النهائية هي المرجع</h2><p className="mt-4 leading-8 text-gray-700">الشروط المعروضة عند الاشتراك هي التي تحدد الأهلية والمبلغ القابل للاسترداد وأي استثناءات مرتبطة بالخدمات أو التكاليف الخارجية المفعلة.</p></div></section>
<FAQ items={faqs} title="الأسئلة الشائعة حول سياسة الاسترداد"/>
<section className="py-16"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black">هل تريد مراجعة حالة اشتراكك؟</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-[#0F3F1A] px-8 py-4 font-black text-white">تواصل مع خدمة العملاء <ArrowLeft className="h-5 w-5"/></Link></div></section>
</main><Footer/></div></>}
