import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { Headphones, Route, FileCheck2, ShieldCheck, Clock3, MessageCircle } from 'lucide-react';

export default function SupportPolicy(){return <><Head><title>سياسة الدعم | بيت الريف</title><meta name="description" content="تعرف على نطاق دعم بيت الريف، طريقة تنظيم الطلبات، قنوات التواصل، وما يشمله الدعم وما يحتاج إلى نطاق خدمة أو اتفاق منفصل."/><link rel="canonical" href="https://bietalreef.ae/support-policy"/></Head><div dir="rtl" className="min-h-screen bg-[#F8FBF9]"><Navbar/><main>
<section className="bg-gradient-to-b from-[#EAF5ED] to-white px-4 py-20 text-center"><div className="mx-auto max-w-5xl"><Headphones className="mx-auto h-12 w-12 text-[#0F3F1A]"/><h1 className="mt-5 text-4xl font-black text-[#0F3F1A] md:text-6xl">سياسة الدعم</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-9 text-gray-600">دعم بيت الريف يركز على التواصل الواضح، تنظيم الطلب، وتوجيه المستخدم إلى المسار الصحيح داخل المنصة أو إلى نطاق خدمة مستقل عند الحاجة.</p></div></section>
<section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[[MessageCircle,'التواصل','استقبال الاستفسارات والمشكلات وطلبات المساعدة عبر قنوات الدعم المتاحة.'],[Route,'التوجيه','توجيه المستخدم إلى القسم أو الخدمة أو مسار التسجيل أو السياسة المناسبة.'],[FileCheck2,'مراجعة الطلب','مراجعة المعلومات المتاحة قبل تحديد الخطوة التالية.'],[ShieldCheck,'حدود واضحة','الدعم لا يغيّر شروط الباقات أو الصلاحيات ولا يعتمد وعودًا غير منشورة.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-[#DCE8DF] bg-white p-7"><I className="h-8 w-8 text-[#0F3F1A]"/><h2 className="mt-4 text-xl font-black">{t}</h2><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
<section className="bg-[#0F3F1A] px-4 py-16 text-white"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">كيف نتعامل مع طلب الدعم؟</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','استقبال الطلب'],['02','تحديد الحساب أو الخدمة'],['03','مراجعة المشكلة أو الاستفسار'],['04','توجيهك إلى الإجراء المناسب']].map(([n,t])=><div key={n} className="rounded-3xl bg-white/10 p-6"><span className="text-[#F3D46B]">{n}</span><h3 className="mt-3 font-black">{t}</h3></div>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-8"><Clock3 className="h-8 w-8 text-[#0F3F1A]"/><h2 className="mt-4 text-2xl font-black">الوقت يعتمد على نوع الطلب</h2><p className="mt-4 leading-8 text-gray-600">الاستفسار البسيط يختلف عن مشكلة حساب أو طلب تقني أو خدمة تحتاج إلى مراجعة بيانات أو مزود خارجي. لذلك لا نضع مدة واحدة لكل الحالات.</p></article><article className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><h2 className="text-2xl font-black">ما لا يغيّره الدعم</h2><p className="mt-4 leading-8 text-gray-700">فريق الدعم لا يتجاوز حالة الحساب أو الخطة أو شروط النشر أو السياسات، ولا يمنح صلاحيات أو مزايا غير مفعلة رسميًا.</p></article></div></section>
<section className="pb-16 text-center"><Link href="/contact" className="inline-flex rounded-2xl bg-[#0F3F1A] px-8 py-4 font-black text-white">تواصل مع الدعم</Link></section>
</main><Footer/></div></>}
