import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import FAQ from '../components/FAQ';
import { ArrowLeft, Bot, FileText, PackageSearch, BriefcaseBusiness, ShieldCheck, Sparkles } from 'lucide-react';

const faqs=[['ما هو وياك؟','وياك مساعد أعمال ذكي من بيت الريف، مصمم للمساعدة في مهام ترتبط بحساب الشركة وبياناتها ومسارات المنصة.'],['هل وياك شات بوت عام؟','لا. دوره الأساسي العمل داخل سياق بيت الريف وبيانات وصلاحيات الحساب.'],['في ماذا يساعد الشركات؟','يساعد في تنظيم المعلومات وصياغة المحتوى وتجهيز بيانات المنتجات والخدمات والعروض والمستندات والإرشاد داخل رحلة العمل بحسب الصلاحيات.'],['هل يتخذ القرار بدل صاحب الشركة؟','لا. يساعد في الفهم والتنظيم والتجهيز، بينما تبقى القرارات النهائية والإجراءات الحساسة بيد المستخدم والجهات المخولة.']];

export default function WeyaakAI(){return <><Head><title>وياك – الذكاء الاصطناعي من بيت الريف | مساعد أعمال ذكي</title><meta name="description" content="تعرف على وياك، مساعد الأعمال الذكي داخل بيت الريف الذي يعمل مع سياق حساب الشركة لمساعدة المحتوى والعناصر والمستندات ومسارات العمل."/><link rel="canonical" href="https://bietalreef.ae/weyaak-ai"/></Head><div dir="rtl" className="min-h-screen bg-[#F7FBF8]"><Navbar/><main>
<section className="relative overflow-hidden bg-[#062F22] py-20 text-white md:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(52,211,153,.2),transparent_32%)]"/><div className="relative mx-auto max-w-7xl px-4 text-center"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 font-black text-emerald-200"><Sparkles className="h-5 w-5"/>وياك | الذكاء الاصطناعي من بيت الريف</span><h1 className="mx-auto mt-6 max-w-5xl text-4xl font-black leading-tight md:text-6xl">مساعد أعمال ذكي يعمل داخل سياق شركتك</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-9 text-white/80">وياك ليس شات بوت عامًا منفصلًا. هو مساعد داخل منظومة بيت الريف يساعد في المحتوى والعناصر والمستندات والمعلومات ومسارات العمل وفق بيانات الحساب والخطة والصلاحيات.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">تعرف على وياك داخل بيت الريف <ArrowLeft className="h-5 w-5"/></Link></div></section>
<section className="mx-auto max-w-7xl px-4 py-16"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[[BriefcaseBusiness,'يفهم سياق النشاط','هوية الشركة والتخصصات والمناطق والبيانات المتاحة للحساب.'],[PackageSearch,'العناصر والمتجر','يساعد في تجهيز معلومات المنتجات والخدمات والعروض وفق المسار المتاح.'],[FileText,'المستندات والمحتوى','تنظيم وصياغة المعلومات والمحتوى والمستندات المرتبطة بالعمل.'],[ShieldCheck,'ضمن الصلاحيات','قدراته ترتبط بحالة الحساب والخطة والصلاحيات والبيانات المتاحة.']].map(([I,t,d])=><article key={t} className="rounded-[2rem] border border-emerald-100 bg-white p-7 shadow-sm"><I className="h-8 w-8 text-[#087A57]"/><h2 className="mt-4 text-xl font-black">{t}</h2><p className="mt-3 leading-8 text-gray-600">{d}</p></article>)}</div></section>
<section className="bg-white py-16"><div className="mx-auto max-w-6xl px-4"><h2 className="text-3xl font-black">كيف يعمل وياك داخل الحساب؟</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{[['01','يفهم سياق حسابك'],['02','تحدد المهمة المطلوبة'],['03','يساعدك داخل المسار المناسب'],['04','تراجع النتيجة وتكمل الإجراء']].map(([n,t])=><div key={n} className="rounded-3xl bg-emerald-50 p-6"><span className="text-3xl font-black text-emerald-700">{n}</span><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section>
<section className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] bg-[#062F22] p-8 text-white"><Bot className="h-9 w-9 text-emerald-200"/><h2 className="mt-5 text-2xl font-black">ذكاء اصطناعي داخل بيئة أعمال حقيقية</h2><p className="mt-4 leading-8 text-white/75">القيمة الأساسية لوياك تأتي من ارتباطه بسياق الشركة ومسارات العمل، وليس من تقديم دردشة عامة بلا سياق.</p></article><article className="rounded-[2rem] border border-[#E6DCC8] bg-[#FFF8E5] p-8"><h2 className="text-2xl font-black">القرار النهائي للمستخدم</h2><p className="mt-4 leading-8 text-gray-700">يساعد وياك في الفهم والتنظيم والتجهيز، لكنه لا يحل محل صاحب الحساب أو الجهة المخولة في القرارات الحساسة أو النهائية.</p></article></div></section>
<FAQ items={faqs} title="الأسئلة الشائعة حول وياك"/>
<section className="bg-[#062F22] py-16 text-white"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black">وياك داخل منظومة بيت الريف</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-emerald-300 px-8 py-4 font-black text-[#062F22]">تحدث مع فريق بيت الريف <ArrowLeft className="h-5 w-5"/></Link></div></section>
</main><Footer/></div></>}
